"""update_relationships_and_fix_circular_deps

Revision ID: 5cb7c3ff240e
Revises: 3c5c7bf53f94
Create Date: 2025-03-11 20:50:52.284867+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5cb7c3ff240e"
down_revision: Union[str, None] = "3c5c7bf53f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "settings")
    # ### end Alembic commands ###
