"""fix_relationship_viewonly_flags

Revision ID: fada5296b4a7
Revises: 1b86f4a88bf0
Create Date: 2025-03-11 21:11:12.257597+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fada5296b4a7"
down_revision: Union[str, None] = "1b86f4a88bf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
