"""change lesson and module name to title

Revision ID: 282a7ba7357b
Revises: ffb9a7a41f30
Create Date: 2025-03-19 12:37:59.087228+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "282a7ba7357b"
down_revision: Union[str, None] = "ffb9a7a41f30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lessons", sa.Column("title", sa.String(length=255), nullable=False)
    )
    op.drop_column("lessons", "name")
    op.add_column(
        "modules", sa.Column("title", sa.String(length=255), nullable=False)
    )
    op.drop_column("modules", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modules",
        sa.Column(
            "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("modules", "title")
    op.add_column(
        "lessons",
        sa.Column(
            "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("lessons", "title")
    # ### end Alembic commands ###
