"""update_relationship_back_populates_and_viewonly

Revision ID: 65a08390d987
Revises: b7a489d06402
Create Date: 2025-03-11 21:15:47.945003+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65a08390d987"
down_revision: Union[str, None] = "b7a489d06402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
