"""make_enrollment_relationships_viewonly

Revision ID: 6c2714f473cc
Revises: 409ce18b6213
Create Date: 2025-03-11 21:17:57.419923+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c2714f473cc"
down_revision: Union[str, None] = "409ce18b6213"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
