"""update course model nullable fields

Revision ID: ffb9a7a41f30
Revises: e1951340c884
Create Date: 2025-03-18 14:37:26.601267+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffb9a7a41f30"
down_revision: Union[str, None] = "e1951340c884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "courses",
        "difficulty_level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="difficulty_level"
        ),
        nullable=True,
        existing_server_default=sa.text("'beginner'::difficulty_level"),
    )
    op.alter_column(
        "courses",
        "grade_level",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "courses",
        "academic_year",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "courses", "sequence_number", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses",
        "sequence_number",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "courses",
        "academic_year",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "courses",
        "grade_level",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "courses",
        "difficulty_level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="difficulty_level"
        ),
        nullable=False,
        existing_server_default=sa.text("'beginner'::difficulty_level"),
    )
    op.alter_column(
        "courses", "description", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###
