"""consolidate_status_fields

Revision ID: 1b86f4a88bf0
Revises: 1f0df90c714e
Create Date: 2025-03-11 21:07:03.997226+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b86f4a88bf0"
down_revision: Union[str, None] = "1f0df90c714e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course_reviews",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "approved", "rejected", "hidden", name="review_status"
        ),
        comment="Status of the review: pending, verified, approved, rejected, or hidden",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::review_status"),
    )
    op.drop_column("course_reviews", "is_verified")
    op.alter_column(
        "courses",
        "status",
        existing_type=postgresql.ENUM(
            "draft", "published", "archived", name="course_status"
        ),
        comment="Status of the course: draft, published, or archived",
        existing_nullable=False,
    )
    op.drop_column("courses", "is_archived")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column(
            "is_archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
            comment="Business-level flag indicating if course is archived. Different from system-level soft delete.",
        ),
    )
    op.alter_column(
        "courses",
        "status",
        existing_type=postgresql.ENUM(
            "draft", "published", "archived", name="course_status"
        ),
        comment=None,
        existing_comment="Status of the course: draft, published, or archived",
        existing_nullable=False,
    )
    op.add_column(
        "course_reviews",
        sa.Column(
            "is_verified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "course_reviews",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "approved", "rejected", "hidden", name="review_status"
        ),
        comment=None,
        existing_comment="Status of the review: pending, verified, approved, rejected, or hidden",
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::review_status"),
    )
    # ### end Alembic commands ###
