"""update user table to remove keys inherited from basemodel

Revision ID: e1951340c884
Revises: dc3b44b5bb96
Create Date: 2025-03-12 07:31:00.605727+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1951340c884"
down_revision: Union[str, None] = "dc3b44b5bb96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
